### ISSUE TITLE
Intent recognition doesn't set custom data

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy-nlu-hermes#3]
I was trying to follow a flow with start/continue/end session messages, and I noticed that the customData field set in a `hermes/dialogueManager/ContinueSession` message isn't copied over to the `hermes/intent/#` message. It seems that rhasspy-nlu-hermes just doesn't set it, so apps listening to the intents can't use custom data.

I have added an example to rhasspy-hermes-app of what I was trying to do: https://github.com/rhasspy/rhasspy-hermes-app/blob/master/examples/continue_session.py

**Comment by coduinix** [comment]
I have the feeling that this commit might help in propagating the `custom_data` through the flow: https://github.com/rhasspy/rhasspy-dialogue-hermes/commit/61a8f64cd57a9ffc7535dfc647da034d41416109

**Comment by StanleyGoffinet** [comment]
have the same issue. The custom_data stay at none in the nluIntent

**Comment by koenvervloesem** [comment]
This should have been fixed now in the [preliminary release of Rhasspy 2.5.10](https://community.rhasspy.org/t/preliminary-release-of-rhasspy-2-5-10/2573).

**Comment by koenvervloesem** [comment]
I have documented how to use `custom_data` in a continued session with Rhasspy Hermes App:

https://rhasspy-hermes-app.readthedocs.io/en/latest/usage.html#continuing-a-session
